apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: goldprice-clickhouse-connector
  labels:
    strimzi.io/cluster: kafka-connect

spec:
  class: com.clickhouse.kafka.connect.ClickHouseSinkConnector
  tasksMax: 1
  config:
    topics: "goldprice.raw"
    hostname: "chi-clickhouse-installation-goldprice-0-0.clickhouse.svc.cluster.local"
    port: "8123"
    username: "admin"
    password: "goldprice_2026"
    database: "raw"
    ssl: "false"
    auto.offset.reset: "earliest"
    schemas.enable: "false"
    topic2TableMap: "goldprice.raw=goldprice_raw"
    # key.converter: "org.apache.kafka.connect.storage.StringConverter"

    # Converter config
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: "false"

    # SMTs config
    transforms: "InsertMetadata"

    # automatically add offset for deduplicate checking
    transforms.InsertMetadata.type: "org.apache.kafka.connect.transforms.InsertField$Value"
    transforms.InsertMetadata.offset.field: "_offset"
    transforms.InsertMetadata.partition.field: "_partition"

    # can have some type forcing here (if needed)

    # error policy
    errors.tolerance: "none"
    errors.log.enable: "true"
    errors.log.include.messages: "true"